### ISSUE TITLE
Use ristretto255 instead of clean 25519

### ISSUE THREAD

**Issue by paulmillr** [zoom/zoom-e2e-whitepaper#1]
To combat small-subgroup attacks, I suggest to use ristretto255 (https://ristretto.group).

It could be used for ECDH etc.

**Comment by dconnolly** [comment]
Examples of doing Schnorr signatures and DH over Ristretto255 :

https://github.com/w3f/schnorrkel
https://github.com/ZcashFoundation/ristretto255-dh

**Comment by paulmillr** [comment]
Ain't eddsa a subset of schnorr signatures?

**Comment by dconnolly** [comment]
> Ain't eddsa a subset of schnorr signatures?

Yes it's a variant; I figured if we're suggesting ristretto for Diffie-Hellman we can also suggest it for signatures.

**Comment by mmou** [comment]
Thanks for the suggestion! We are fans of misuse-resistant crypto APIs, such as that exposed by Ristretto. 

Our current plan, since we’re only doing simple signing and key exchange operations, and given our platform integration needs, is to use libsodium's Ed25519 and Curve25519 implementations, which to our understanding do the requisite cofactor misuse-related checks (e.g. https://github.com/jedisct1/libsodium/commit/c190574cee382ace1ee0f8fdacc136f1797287e6, https://github.com/jedisct1/libsodium/commit/4099618de2cce5099ac2ec5ce8f2d80f4585606e). 

Additionally, if any future development requires arithmetic on unclamped keys, future use/interoperability with Ristretto seems possible.

- Zoom E2E Team
