### ISSUE TITLE
Enhancements to Cloud Recordings

### ISSUE THREAD

**Issue by 0zAND1z** [zoom/zoom-e2e-whitepaper#10]
Based on the paper, it looks like Cloud Recordings capture the "decrypted stream" and store it on Zoom's own infrastructure.

I suggest the team to allow the meeting host to store recordings on a cloud of their own choice. Zoom cloud, OndeDrive, Google Drive, and MoiBit should be some of the options.

In contrast to the traditional cloud platforms mentioned above, [MoiBit](https://www.moibit.io/) is an IPFS-based cloud for enterprises and developers. MoiBit is used to store data and ensure the integrity of data along with inherent cryptographic proofs available within the network.

All the above platforms offer feature-rich SDKs. I suggest to have a look at them and open up the choice of storage for Cloud Recording for both individual users and enterprise users who'd like to manage the recordings in their own environments.

**Comment by kray543** [comment]
Note the cloud recordings are also streamed from AKAMAI where they are decrypted and recencrypted when served out.

**Comment by karanlyons** [comment]
In the current model Cloud Recordings work by having a Cloud Recording Agent which is invited by the host and joins like any other user, allowing it to capture higher quality audio and video than the user themselves may be able to given their bandwidth and computational constraints. We offer local storage for recordings in Zoom Meetings as well, for those who would prefer not to store that data in the cloud.

We think this offers the best of both worlds since users can either opt to stay entirely within our platform, and reap the benefits of offloading that recording workload or have the freedom to choose any form of storage they’d prefer without having to invite us in.
