### ISSUE TITLE
“double up” in Section 3.5 not required for FIPS 

### ISSUE THREAD

**Issue by rt-acumen** [zoom/zoom-e2e-whitepaper#11]
Hi there, 

My comment/issue is pertaining to Section 3.5 in the whitepaper. I think you can safely skip the “double up” for all public key operations and still meet current (and future) FIPS requirements. 
There is an Implementation Guidance (https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Module-Validation-Program/documents/fips140-2/FIPS1402IG.pdf) that allows these curves for FIPS 140-2 under the CMVP. IG A.2 explicitly permits the use of non-NIST-recommended curves in a module's Approved mode of operation. 

There are also two draft publications (FIPS 186-5 and SP 800-186) that (when published) will formally recognize the curves in Section 3.5 as FIPS Approved. Public comment period closed in January 2020. Section 7.1 in the draft of FIPS 186-5 (https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf) identifies Edwards-curve Digital Signature Algorithms and considers them Approved (as long as the "shall" statements are met). Curve25519 is identified in Section 4.2 of SP 800-186 (https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-186-draft.pdf). ACVP validation testing (https://usnistgov.github.io/ACVP/) for these algorithms should follow once FIPS 186-5 and SP 800-186 are published. Until ACVP testing is available a these functions can be included in the module's Approved mode of operation as "vendor affirmed". 

If the plan is to pursue a FIPS validation FIPS 140-2 IG A.2 can be used as a stop gap for implementing these in FIPS Approved mode until the final versions of the NIST publications and ACVP testing are available. I will also note there are some shall statements in the IG that need to be followed and some documentation-related requirements that would need to be met (for a formal FIPS validation). I can elaborate on those in detail if there is value. 

BTW, I am the Lab Manager at an accredited FIPS lab. Let me know if I can be of further assistance with navigating any other of the CMVP/FIPS related challenges. 

Best Regards
Ryan

**Comment by ApolloLV** [comment]
I am also much in favor of not baking something into the protocol now that is already expected to be obsolete soon. This could lead to interesting issues along the road (downgrade attacks would come to mind if the verification is not implemented carefully) while making the life of both implementers and researchers attempting a proof harder than absolutely necessary.

**Comment by AdriaanDeVos** [comment]
The goal of this paper is to meet current FIPS requirements as soon as possible, while already implementing the new FIPS 186-5. This enables usage of Zoom applications for governments while waiting for FIPS 186-5 release.  
_"Therefore, in some cases (like government uses that require FIPS certification) we must fall back to FIPS-approved algorithms"_

The paper shows that they aim to only use the new certification when it is released.  
_"Once certification succeeds, we can safely “no-op” the operations over P-384."_

I agree that a "double up" on all public key operations might not be the correct way to go to get certified because of performance and implementations risks. As rt-acumen said, it should definitely be considered using non-NIST-Recommended Asymmetric Key Sizes and Elliptic Curves as defined in `FIPS 140-2 IG A.2`

**Comment by karanlyons** [comment]
Thanks for your thorough comments! We found them exceedingly useful. We will be offering e2e as a configurable option and believe that the drafts will make it to the published stage in due course; as such we will remove the DualSign operations in favor of a cleaner, single curve approach.
