### ISSUE TITLE
Some feedback on whitepaper

### ISSUE THREAD

**Issue by jonnadul** [zoom/zoom-e2e-whitepaper#25]
Overall well written and thought out, but had some feedback/comments.

-- **[Section 1.2]**: [Advanced persistent threads](https://en.wikipedia.org/wiki/Advanced_persistent_threat) are the new normal in today's thread landspace and assuming an outside actor cannot gain access into internal infrastructure is flawed and operating in an assumed breach mindset is a must.
-- **[Section 1.3]**: Maintaining E2E encryption and privacy in a group chat environment is very much a solved problem, see [Signal's implementation](https://signal.org/blog/private-groups/).
-- **[Section 3.6]**: The long-term IVK<sub>i</sub> ISK<sub>i</sub> keypairs seem to be the root of trust the rest of the PKI is built on top of. Recommend using a hardware secure key storage volume, like a TPM-based KSP or Yubikey-based KVM, if available.
-- **[Section 3.7]**: Would a participant who has multiple Zoom clients each have their own long-term key pairs? If so wouldn't the leader have to perform a participant join call on each of these clients if the participant wants to switch between clients?
-- **[Section 3.8]**: Why truncate the SHA-256 result to 128 bits? Wouldn't that increase chance for collision?
-- **[Section 4.1.2]**: Using a centralized certificate vs self-signed certs would allow for using a CRL which would make revocation of certificates easier.

_All views and opinions expressed are solely my own and do not express the views or opinions of my employer or affiliated organizations_

**Comment by karanlyons** [comment]
> -- [Section 1.2]: Advanced persistent threads are the new normal in today's thread landspace and assuming an outside actor cannot gain access into internal infrastructure is flawed and operating in an assumed breach mindset is a must.

We agree! The goal of this paper is to reduce the amount of trust that any user would need to place in the security of the Zoom infrastructure.

> -- [Section 1.3]: Maintaining E2E encryption and privacy in a group chat environment is very much a solved problem, see Signal's implementation.

Running a video call for up to one thousand people in an E2E encrypted manner is not a solved problem. Thus this paper! Signal has done fantastic work, but it sadly does not solve this problem.

> -- [Section 3.6]: The long-term IVKi ISKi keypairs seem to be the root of trust the rest of the PKI is built on top of. Recommend using a hardware secure key storage volume, like a TPM-based KSP or Yubikey-based KVM, if available.

These keys will be generated and stored within a TEE whenever supported by the OS and hardware a Zoom client is running on. See #5.

> -- [Section 3.7]: Would a participant who has multiple Zoom clients each have their own long-term key pairs? If so wouldn't the leader have to perform a participant join call on each of these clients if the participant wants to switch between clients?

We currently plan to support the current behaviour of the Zoom client, which is to join separately for each device.

> -- [Section 3.8]: Why truncate the SHA-256 result to 128 bits? Wouldn't that increase chance for collision?

We are truncating to a length that is still resistant to collision while providing a reasonable user experience with the security code.

> -- [Section 4.1.2]: Using a centralized certificate vs self-signed certs would allow for using a CRL which would make revocation of certificates easier.

We are using a distributed model of key generation combined with a transparency tree in order to avoid centralized trust in the Zoom infrastructure.
