### ISSUE TITLE
Trade-offs between stronger identity and privacy / respect

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [zoom/zoom-e2e-whitepaper#29]
Thank you so much for sharing this roadmap and thank you for reading this comment even though I'm posting it late!

As you strengthen the notion of identity in Phases 2-4, there seem to be some trade-offs between the security provided by stronger identity guarantees and user-privacy / user-respect. Perhaps some of these tradeoffs must be fixed by the design; are there any that can be decided on a per-call basis by users or that have tricks to getting positive outcomes and avoiding the tradeoff. For example, could you share more of your thinking around the following situations?

1) Names, display names, and enterprise SSO identity information
Section 4.1.1 mentions that the identity statement "for those who authenticate via SSO identity providers" (IDPs) will include whatever identity information that the IDP provides. I don't have a great understanding of what information is available via IDPs (and whether it might be considered expected or unexpected by users), but, based on my university's use of SSO for Zoom, it seems that one piece of information coming from the IDP is a name (which Zoom appears to use currently as a default display name). While names can be very useful identifying information, it seems that what is coming from the IDP here is a full (legal?) name, rather than the name folks use with their colleagues on a daily basis, and I imagine that if one IDP is doing this, many others are as well. Zoom's current feature of allowing users to change their display name - to hide a middle name they don't normally use, replace a first name with a nickname, add their pronouns, etc. - gives users the opportunity to display the name they prefer to their colleagues. How does this change with names baked into the identity information? Can users still define their identity to their enterprise colleagues based on the name they prefer, even though the IDP has tied their email & public key to a name they don't prefer? If a user's legal name changes in the IDP's records, is the timing of that change then broadcast to all via the ZTT in Phase 3+? Can users hide legal names (or other IDP-provided information that they don't want to share) from ever appearing in plaintext in the ZTT? The current solution with display names adds a lot of respectful flexibility (in one meeting I'm <full name>, in the next I'm <initials and pronouns>, in the next I'm <first name and pronouns>, etc.); can you maintain that even while strengthening identity?

2) Privacy for Contact List Updates
Section 4.1.5 in Phase 2 describes a sigchain of Contact List Updates mapping users seen in meetings to the tail of their identity sigchain at the time. Further, this contact list sigchain can be transferred between devices, and the whitepaper doesn't describe any interaction between devices to do so. Section 5.2.5 mentions that these contact lists are "now also stored in the ZTT" in Phase 3. This sounds an awful lot like a temporally ordered list of everyone I've ever had a Zoom meeting with, which I certainly would not want to be public! I'd prefer that that information was not kept long-term at all, except where absolutely necessary. This sort of metadata is a fruitful target for all sorts of privacy-attacking adversaries.
Section 4.1.4 mentions a neat use of commitments to hide a user's chosen device name from the sigchain. Are you planning to do something similar with Contact List Updates to mitigate the privacy risk? If so, how can the user know or control how long these meeting contact records are kept for? If using the strategy from Section 4.1.4, is there any benefit to storing the lists on the ZTT, since the server would still hold the random values? Section 5.2.5 mentions using the ZTT as a more trustworthy mechanism for relaying changes between client devices than just trusting the server; is there a way to preserve the utility of this feature for each user without allowing anyone else to read their contact lists?

3) Although the paper mentions that the commitment scheme in Section 4.1.4 is hidden in the rest of the document, it would be really useful to have more examples of when such commitments can be used in Phases 3 and 4, and when the stronger guarantees in those later stages make this challenging.

I'd appreciate any other thoughts or scenarios you can share around these stronger-identity vs privacy&respect trade-offs. 

Thank you very much!
Anna Kornfeld Simpson
PhD Student, University of Washington

[Edit: formatting]

**Comment by AMarcedone** [comment]
Thanks for your thoughtful questions. We are thinking hard about the tradeoffs between the need to establish identity and prevent impersonations and the need for users to express themselves and protect their privacy. As we finalize the design for the following phases, we will be sharing additional documents which will provide more details on most of these points. In the meantime, let us offer some preliminary comments:

1. We think that it’s reasonable to display the email address in a meeting as a default. Because the names stored in an IdP’s database will often come from a centralized system like a HRIS, we’re aware that not every organization will keep them up to date. People change their names for a wide variety of meetings and these out-of-date names may not be appropriate to display. We haven’t finalized the product design, but we are taking these factors into account. About the ZTT in particular, several things should mitigate your concerns: (1) the ZTT will probably not include someone’s name (2) personal information in the ZTT can be removed by removing the entry, only a stub will remain (3) we will enforce access control on the values stored on the ZTT so that the information about a user are visible only to parties who need such information to communicate with that user. In particular, we could enforce different policies if you are looking up a user who is part of your own organization vs a different one. 

2. The ZTT entries aren’t public, but we hear you on that concern and it’s a good one. As we design out this section in detail we will take this into account.
