### ISSUE TITLE
A hodgepodge of clarification questions/nits

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [zoom/zoom-e2e-whitepaper#30]
Thank you for such a well-written paper! I'm including a set of clarification questions that I'm fairly certain were not in any previous comments.

1. At the beginning of Section 3.5, could you please write out the arguments and return value for HKDF as you do for EdDSA, DH, AES, etc.? The cited paper and the RFC both show HKDF as having 4 arguments, while this paper writes out only 2 of them.
2. Section 3.7: Can a user still be logged into the same meeting from two devices at once? (This seems to appear in instructional settings, for example if the teacher plans to annotate slides on a tablet but still wants to be visible to students via a webcam on a second device.) How to disambiguate the `Sig_i` for the user's two devices?
3. If the leader has multiple devices, should I read steps like Section 3.8 step 1 (and its modification in later phases) as fetching IVK_l for all the leader's devices and Section 3.8 step 5 as trying each of them until finding the one that works?
4. Potential typo: I think the the last word of Section 3.8 step 5 should be `binding_l` rather than `binding_i`
5. Could you provide some intuition on why key rotation (3.8.1) happens at most every 15 seconds and heartbeats (3.8.2) at least every 10 seconds? Are these two values related?
6. What content is in the "heartbeat" (3.8.2)?
7. Section 3.8.2: is `t` reset within recurring meetings? (i.e. if I have a weekly meeting is `t` at zero when the meeting begins each week or does it keep growing?)
8. Section 3.8.2/3.8.4/3.8.10: Is there any way for a client to signal "help I didn't get the current mk / I can't decrypt" besides dropping out & rejoining the meeting?
9. Section 4.1.1 says "later signatures should be computed over the statement body and previous signatures". If there's an SSO IDP, how does the signature from Zoom's servers make it into the content that the IDP signs? Is there a standard API to tell an IDP "please sign everything you just sent me and also this concatenated blob"?
10. Some performance questions: 
        i) Section 4.1.1 (and again in later phases that add information to the user's IVK statement): since the leader now has more signatures to verify per participant, does having many participants join at once cause latency challenges for the leader?
        ii) Section 5.2.4: Sometimes an invited meeting attendee not yet have the Zoom client installed on that device when they attempt to join the meeting. With the additional ZTT requirements, is there any increased time between installation of the Zoom client and the moment they can join the meeting? Does it become more important from a UX perspective to have attendees install the client in advance?

Thanks for taking the time to read this even though I posted it late.

Anna Kornfeld Simpson
PhD Student, University of Washington

**Comment by karanlyons** [comment]
> Thank you for such a well-written paper! I'm including a set of clarification questions that I'm fairly certain were not in any previous comments.

Thank you for your questions. We are trying to be clear, but clearly it’s hard 😉

> At the beginning of Section 3.5, could you please write out the arguments and return value for HKDF as you do for EdDSA, DH, AES, etc.? The cited paper and the RFC both show HKDF as having 4 arguments, while this paper writes out only 2 of them.

We’re listing only the key and info arguments, implying some consistent hash function and use of a salt.

> Section 3.7: Can a user still be logged into the same meeting from two devices at once? (This seems to appear in instructional settings, for example if the teacher plans to annotate slides on a tablet but still wants to be visible to students via a webcam on a second device.) How to disambiguate the Sig_i for the user's two devices?

They can; keypairs are per device, meaning Sig<sub>i</sub> is disambiguated.

> If the leader has multiple devices, should I read steps like Section 3.8 step 1 (and its modification in later phases) as fetching IVK_l for all the leader's devices and Section 3.8 step 5 as trying each of them until finding the one that works?

The leader is really the leading *device* rather than the leading user, so you can read it as a single device performing the actions.

> Potential typo: I think the the last word of Section 3.8 step 5 should be binding_l rather than binding_i

I believe it *is* meant to be binding<sub>i</sub>: our intent is to verify the signature generated in 3.7.1 step 4.

> Could you provide some intuition on why key rotation (3.8.1) happens at most every 15 seconds and heartbeats (3.8.2) at least every 10 seconds? Are these two values related?

These numbers are a bit arbitrary. Our intent here is to balance security against the performance of ongoing rekeys and heartbeats, though these values may change as we develop stronger performance benchmarks.

> What content is in the "heartbeat" (3.8.2)?

The heartbeat contains a signed payload of `"Zoom00LPL\0"` ∥ binding<sub>l</sub> ∥ SHA256(LPL<sub>v</sub>) ∥ v ∥ t ∥ mkSeqNum.

> Section 3.8.2: is t reset within recurring meetings? (i.e. if I have a weekly meeting is t at zero when the meeting begins each week or does it keep growing?)

t would be reset between instances of the same recurring meeting, as will the bulletin board: the meetingUUID would be different for each “instance” of the recurring meeting.

> Section 3.8.2/3.8.4/3.8.10: Is there any way for a client to signal "help I didn't get the current mk / I can't decrypt" besides dropping out & rejoining the meeting?

Currently there is not; As this data is sent over a TCP channel it should always make it...eventually.

> Section 4.1.1 says "later signatures should be computed over the statement body and previous signatures". If there's an SSO IDP, how does the signature from Zoom's servers make it into the content that the IDP signs? Is there a standard API to tell an IDP "please sign everything you just sent me and also this concatenated blob"?

The intent would be for the IdPs to support such an API, and for the device to relay Zoom’s signed statement to the IdP (after validating that it is accurate).

> Some performance questions:
> i) Section 4.1.1 (and again in later phases that add information to the user's IVK statement): since the leader now has more signatures to verify per participant, does having many participants join at once cause latency challenges for the leader?

It might! These operations should be fairly fast relative to the wall clock time, though, and so any performance issues should be largely unnoticeable.

> ii) Section 5.2.4: Sometimes an invited meeting attendee not yet have the Zoom client installed on that device when they attempt to join the meeting. With the additional ZTT requirements, is there any increased time between installation of the Zoom client and the moment they can join the meeting? Does it become more important from a UX perspective to have attendees install the client in advance?

There shouldn’t be any noticeable delays incurred by the use of the ZTT, though the changes to the ZTT may not have been audited by a third party before they need to be accepted by the host, i.e., the relationship between the host and that user may be subject to weaker security with regards to server equivocation for a period of time.
