### ISSUE TITLE
Local Key Security for shared device use case

### ISSUE THREAD

**Issue by kiranszone** [zoom/zoom-e2e-whitepaper#41]
it's not clear how zoom will manage Local Key Security, when the device and local credential shared between users, but not the zoom account details. Just relying on the local device keychain wouldn't be sufficient.

**Comment by kiranszone** [comment]
Secition 3.11 talks about generating rank string KWK, but doesn't talk about how it's protected between users.

**Comment by maxtaco** [comment]
The KWK is stored on the server and to fetch it, the user must be logged into zoom (via SSO or username/password). So if Alice and Bob share the same macOS account, if Alice logs into Zoom as Alice, she'll get her KWK and will be able to decrypt her local key in the OS Account, but not Bob's, since she can't get Bob's KWK.

Best effort here of course since Alice and Bob sharing the same macOS account can root each other in a number of ways we can't protect against.
