### ISSUE TITLE
Use of frequent key rotation

### ISSUE THREAD

**Issue by mark-loveless** [zoom/zoom-e2e-whitepaper#6]
### Current

In section 3.8.1 of your whitepaper, you mention mk being rotated after a participant joins or leaves.

### Proposed

In addition to this rotation, perform a rotation every 15 minutes. Worse case scenario is that in the event of a compromised key, at max 15 minutes of data could be compromised.

**Comment by dconnolly** [comment]
Related to this issue, I wonder if the authors had looked at using something like [TreeKem](https://tools.ietf.org/id/draft-ietf-mls-protocol-09.html#rfc.section.5)¹ or other [asynchronous ratcheting trees](https://eprint.iacr.org/2017/666.pdf) for managing the participants per-meeting ephemeral keys and the key rotation of the meeting key. It's not a one-to-one drop in but it is doing a lot of the same work.

¹ See also the updated Tainted TreeKEM: https://eprint.iacr.org/2019/1489.pdf

**Comment by mmou** [comment]
Thanks for the note! We’re still considering how to balance the performance overhead of rekeys with the security controls we’d like to provide to users in meetings, but we agree that we’d like to be able to provide the strongest FS guarantees reasonably practical. 
As for (T)TKEM, you’re right it’s not a straight drop-in, because participants entrust the host to do rotation of the meeting symmetric key, as the simplest way to build upon the existing encryption. We’ll keep tabs especially on any perf research with regards to (T)TKEMs.

-- Zoom E2E Team
