### ISSUE TITLE
Define Trust Model of System Components

### ISSUE THREAD

**Issue by chelseakomlo** [zoom/zoom-e2e-whitepaper#8]
In Section 3.4, several system components are defined, including an identity management system and a bulletin board. Currently, the trust allotted to each component is not well defined, nor the assumed behavior (honest but curious, actively malicious, etc). 

These details are important, as they impacts the resulting security model. For example, currently the bulletin board is supposed to be an untrusted entity whose misbehavior can only result in a denial of service attack (Section 3.7). However, if the identity management system and the bulletin board collude, users' conversations can trivially be compromised. Further, it is unclear what security properties are impacted if the bulletin board shows different views to different participants, or injects additional key material not linked to any specific meeting participant (such as by posting keys owned by Zoom itself).

**Comment by AdriaanDeVos** [comment]
I agree that the trust/behavior can be expanded upon for the several system components.

However, I do not agree with your statement of calling the bulletin board an untrusted entity that could result in a DoS attack. The paper states that the security of the Bulletin Board is managed by the MMR through a reliable signaling channel. This means that it should be as secure as the A/V that is received from the MMR.

The DoS attack on the bulleting board you mentioned is not clear to me. An other possible attack on this system component has been described in section 3.8.4. This subsection takes into account your point of different views per participants, and shows that a mismatch or incorrect information within the bulletin board will cause participants to simply not be able to decrypt the packets.

Your comment about posting keys owned by Zoom itself in the Bulletin Board should not be a big problem because the keys will be visible to all authenticated members.The UI should ensure that a message is shown when a new user has joined, or make it easily visible which members are authenticated for the meeting.

**Comment by LeaKissner** [comment]
Thank you for your thoughtful question. We started writing out an answer to this question and it quickly became rather long and needed the context of the rest of the document. We will clarify the trust model in the next version of the document, as we think that’ll be the easiest way to clarify.
